### PR TITLE
Include go mod vendor to resolve licensei detection failures

### PR DESCRIPTION
**Pull request by nishantapatil3**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| API breaks?     | no
| Deprecations?   | no
| Related tickets | fixes random licensei check failures
| License         | Apache 2.0

### What's in this PR?
Include `go mod vendor` stage in github actions to avoid false-positive when modules github repo could not be determined

### Why?
licensei check fails randomly sometimes when github repo license could not be determined

### Checklist
- [x] Implementation tested
- [x] Error handling code meets the [guideline](https://github.com/banzaicloud/pipeline/blob/master/docs/error-handling-guide.md)
- [x] Logging code meets the guideline
- [x] User guide and development docs updated (if needed)

### CODE REVIEW

**Comment by nishantapatil3** [comment]
Source link where this solution was discussed: https://github.com/banzaicloud/koperator/pull/853#discussion_r961651920

**Comment by sagikazarmark** [comment]
Opened an issue to improve VCS detection: https://github.com/goph/licensei/issues/44

**Comment by sagikazarmark** [comment]
@nishantapatil3 haven't used licensei for a while.

If you could open an issue/discussion with some feedback and the latest pain points and what kind of solution you would prefer, it would be helpful.

Thanks!

**Review by Laci21 — APPROVED** [review]
lgtm

**Comment by nishantapatil3** [comment]
Thanks for the approval @Laci21

**Comment by nishantapatil3** [comment]
> @nishantapatil3 haven't used licensei for a while.
> 
> If you could open an issue/discussion with some feedback and the latest pain points and what kind of solution you would prefer, it would be helpful.
> 
> Thanks!

Yes definitely @sagikazarmark! I'll put together few points that can improve licensei 🚀

**Pull request merged**
