### PR TITLE
Istio 1.2.2 support

### PR DESCRIPTION
**Pull request by waynz0r**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| API breaks?     | no
| Deprecations?   | no
| Related tickets | 
| License         | Apache 2.0

### What's in this PR?

Adds support for Istio `1.2.x` and makes `1.2.2` the default version on the `release-1.2` branch

### Checklist

- [x] Implementation tested

### To Do

- [x] Implement sidecar always/never injection policy
- [x] Implement workloadCertTTL option
- [x] Update upgrade docs

### CODE REVIEW

**Comment by Laci21** [comment]
Thank you very much @waynz0r!

**Comment by zachaller** [comment]
When can we expect the docker hub images to show up for this?

**Comment by Laci21** [comment]
Hi @zachaller,

It was pushed just now: `banzaicloud/istio-operator:0.2.0`

**Comment by zachaller** [comment]
The manifest is currently using latest-1.2 so that tag dose not match.

**Comment by Laci21** [comment]
> The manifest is currently using latest-1.2 so that tag dose not match.

You're right, `banzaicloud/istio-operator:latest-1.2` is also available now.

**Comment by zachaller** [comment]
Thanks!! Working great now.

**Pull request merged**
