### PR TITLE
proxy.istio.io/config annotation does not add env variable in istio-proxy container

### LINKED ISSUE #489: proxy.istio.io/config annotation does not create env variable in side car
**Describe the bug**

Below annotation should add OUTPUT_CERTS env variable to istio-proxy container. But it does not add.

proxy.istio.io/config: |
   proxyMetadata:
      OUTPUT_CERTS: /etc/istio-certs

**Steps to reproduce the issue:**

Add below annotation and check istio container. There is no OUTPUT_CERTS env var created
        sidecar.istio.io/inject: "true"
        proxy.istio.io/config: |
          proxyMetadata:
            OUTPUT_CERTS: /etc/istio-certs

**Expected behavior**

istio proxy container should env var as OUTPUT_CERTS: /etc/istio-certs

istio version : 1.6.8
istio operator image : 0.6.9

### PR DESCRIPTION
**Pull request by satishmane**
https://github.com/banzaicloud/istio-operator/issues/489

proxy.istio.io/config annotation does not create env variable in istio-proxy container

| Q               | A
| --------------- | ---
| Bug fix?        |  yes
| New feature?    | no
| API breaks?     | no
| Deprecations?   | no
| Related tickets | fixes #489
| License         | Apache 2.0

### What's in this PR?
proxy.istio.io/config annotation does not add env variable in istio-proxy container

### Why?
side injector configmap does not read proxy config annotations env vars in istio container

### CODE REVIEW

**Comment by satishmane** [comment]
Hi @Laci21 
I need thix fix asap. Can you please release new bumped up version. thanks

**Review by Laci21 — APPROVED** [review]

**Review by waynz0r — APPROVED** [review]
thanks @satishmane!

**Comment by satishmane** [comment]
@Laci21 @waynz0r for approving quickly. Now I am waiting for new image. My deployment is stuck. Please help

**Comment by Laci21** [comment]
> thanks @Laci21 @waynz0r for approving quickly. Now I am waiting for new image. My deployment is stuck. Please help

We'll release a new version in a few.

**Comment by Laci21** [comment]
@satishmane, `banzaicloud/istio-operator:0.6.10` is released with your fix.

**Comment by satishmane** [comment]
thanks @Laci21 @waynz0r 
I tried with new image. It is giving below error when creating istio cr. Is this broken?

ME                                                                                 STATUS            ERROR   INGRESS IPS   AGE
istio-sample                                                                         ReconcileFailed   failed to reconcile resource: creating resource failed: clusterroles.rbac.authorization.k8s.io "istiod-cluster-role" is forbidden: user "system:serviceaccount:istio-system:istio-operator" (groups=["system:serviceaccounts" "system:serviceaccounts:istio-system" "system:authenticated"]) is attempting to grant RBAC permissions not currently held:
{APIGroups:["networking.x-k8s.io"], Resources:["*"], Verbs:["get" "watch" "list"]}                     3m48s

This corrupted whole thing.. It did not let me uninstall either. istio-sample just stuck there

kubectl delete istio istio-sample -n istio-system .. It is not deleting this CR. it just stuck at below message
istio.istio.banzaicloud.io "istio-sample" deleted

minikube version
minikube version: v1.10.1
commit: 63ab801ac27e5742ae442ce36dff7877dcccb278


kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-17T08:59:10Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by satishmane** [comment]
@Laci21 
I cleaned up banzai istio crd by patching to remove finalizer. It got then deleted. I reinstalled by istio-sample cr to istio-xyz. It worked, but ingress gateway reconciled failed with error message though ingress pod is running

{"level":"info","ts":1597897377.409565,"logger":"controller","msg":"Reconciled","trigger":"istio-system/istio-xyz","correlationID":"b601f594-721e-4cb5-aa10-83b21839a83d","component":"egressgateway"}
{"level":"info","ts":1597897377.409643,"logger":"controller","msg":"ingress gateway address pending: gateway is pending"}
{"level":"info","ts":1597897377.4183455,"logger":"controller","msg":"Istio state updated","trigger":"istio-system/istio-xyz","correlationID":"b601f594-721e-4cb5-aa10-83b21839a83d","status":"ReconcileFailed"}
{"level":"info","ts":1597897379.6544642,"logger":"controller","msg":"mesh gateway state updated","trigger":"istio-system/istio-ingressgateway","correlationID":"876cd097-358a-4dc5-88d7-b030045c008e","status":"Reconciling"}
{"level":"info","ts":1597897379.6545894,"logger":"controller","msg":"Reconciling","component":"meshgateway"}
{"level":"info","ts":1597897379.6607106,"logger":"controller","msg":"Reconciled","component":"meshgateway"}
{"level":"info","ts":1597897379.6609309,"logger":"controller","msg":"gateway address pending: ingress gateway endpoint address is pending"}
sh

**Comment by satishmane** [comment]
I cleaned up everything. I installed again. Now getting some other errors... Not sure what is going on here?


{"level":"error","ts":1597901742.3578713,"logger":"kubebuilder.controller","msg":"Reconciler error","controller":"istio-controller","request":"istio-system/istio-pge","error":"could not reconcile istio: failed to reconcile dynamic resource: creating resource failed: Internal error occurred: failed calling webhook \"validation.istio.io\": Post https://istiod.istio-system.svc:443/validate?timeout=30s: service \"istiod\" not found","errorVerbose":"Internal error occurred: failed calling webhook \"validation.istio.io\": Post https://istiod.istio-system.svc:443/validate?timeout=30s: service \"istiod\" not found\ncreating resource failed\ngithub.com/banzaicloud/istio-operator/pkg/k8sutil.(*DynamicObject).Reconcile\n\t/go/src/github.com/banzaicloud/istio-operator/pkg/k8sutil/unstructured.go:62\ngithub.com/banzaicloud/istio-operator/pkg/resources/citadel.(*Reconciler).Reconcile\n\t/go/src/github.com/banzaicloud/istio-operator/pkg/resources/citadel/citadel.go:139\ngithub.com/banzaicloud/istio-operator/pkg/controller/istio.(*ReconcileIstio).reconcile\n\t/go/src/github.com/banzaicloud/istio-operator/pkg/controller/istio/istio_controller.go:353\ngithub.com/banzaicloud/istio-operator/pkg/controller/istio.(*ReconcileIstio).Reconcile\n\t/go/src/github.com/banzaicloud/istio-operator/pkg/controller/istio/istio_controller.go:237\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.9/pkg/internal/controller/controller.go:215\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.9/pkg/internal/controller/controller.go:158\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181126123746-eddba98df674/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181126123746-eddba98df674/pkg/util/wait/wait.go:134\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181126123746-eddba98df674/pkg/util/wait/wait.go:88\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357\nfailed to reconcile dynamic resource\ncould not reconcile istio","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.9/pkg/internal/controller/controller.go:217\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.9/pkg/internal/controller/controller.go:158\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181126123746-eddba98df674/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181126123746-eddba98df674/pkg/util/wait/wait.go:134\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181126123746-eddba98df674/pkg/util/wait/wait.go:88"}

**Comment by satishmane** [comment]
@Laci21 
0.6.10 Worked on other env. I can see certs now on /etc/istio-certs volumeMount
thanks

**Comment by Laci21** [comment]
Great, thank you for your contribution!

**Pull request merged**
